name: uc-python
channels:
    - defaults
    - conda-forge
dependencies:
    - python>=3.8
    - pip>=20.0
    - numpy=1.18
    - pandas=1.0
    - seaborn=0.10
    - rise=5.6
    - pip:
      - jupyter-contrib-nbextensions
