name: intro-python-datasci
channels:
    - defaults
    - conda-forge
dependencies:
    - python=3.7
    - numpy=1.16
    - pandas=0.24
    - seaborn=0.9
    - rise=5.5
    - pip:
      - jupyter-contrib-nbextensions
